services:
  edgebroker:
    image: rabbitmq:management-alpine
    volumes:
      - VIDEO_BROKER_DATA:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_HIPE_COMPILE=1
    ports:
      - 5672:5672
      - 15672:15672
      - 15674:15674
      - 5552:5552
    networks:
      - ac3
networks:
  ac3:
    external: true

volumes:
  VIDEO_BROKER_DATA:

