spring.main.web-application-type: none

spring.rabbitmq.host: ${rabbitmq.server}
spring.rabbitmq.port: ${rabbitmq.port}
spring.rabbitmq.username: ${rabbitmq.username}
spring.rabbitmq.password: ${rabbitmq.password}
spring.multirabbitmq.serverB.host: ${rabbitmq.serverB.host}
spring.multirabbitmq.serverB.port: ${rabbitmq.serverB.port}
spring.multirabbitmq.serverB.username: ${rabbitmq.serverB.username}
spring.multirabbitmq.serverB.password: ${rabbitmq.serverB.password}

logging:
  level:
    net.sparkworks.common: DEBUG

rabbitmq:
  queueCommands: "${rabbitmq.uriPrefix}-commands"
  queueSend: "${rabbitmq.uriPrefix}-send"
  serverB:
    queueData: ipn-mouse-data-sparks
    queueData2: ipn-mouse-data-sparks2
    queueData3: ipn-mouse-data-sparks3

mapper:
  skinresponse:
    threshold: 5

sparks:
  cargo:
    address: https://api.sparkworks.net
    internal: false
    oauth2:
      client:
        accessTokenUrl: "https://sso.sparkworks.net/aa/oauth/token"
