rabbitmq:
  server: "${SPARKS_RABBIT_HOST}"
  port: "${SPARKS_RABBIT_PORT}"
  username: "${IPN_MAPPER_CLIENT_ID}"
  password: ${smartwork_ipn_mapper_client_secret}
  uriPrefix: "smartwork-ipn"
  serverB:
    host: "${SMARTWORK_RABBIT_HOST}"
    port: "${SMARTWORK_RABBIT_PORT}"
    username: "${SMARTWORK_RABBIT_USERNAME}"
    password: ${smartwork_rabbitmq_pass}

sparks:
  cargo:
    oauth2:
      client:
        clientId: ${IPN_MAPPER_CL}
        clientSecret: ${IPN_MAPPER_CS}
        username: ${IPN_MAPPER_USERNAME}
        password: ${IPN_MAPPER_PASSWORD}
logging:
  level:
    net.sparkworks.common: ERROR
    net.sparkworks.mapper: INFO
