rabbitmq:
  server: "${SPARKS_RABBIT_HOST}"
  port: "${SPARKS_RABBIT_PORT}"
  username: "${IPN_MAPPER_CLIENT_ID}"
  password: ${smartwork_ipn_mapper_client_secret}
  uriPrefix: "smartwork-ipn"
  queueCommands: "${rabbitmq.uriPrefix}-commands"
  queueSend: "${rabbitmq.uriPrefix}-send"
  serverB:
    host: "${SMARTWORK_RABBIT_HOST}"
    port: "${SMARTWORK_RABBIT_PORT}"
    username: "${SMARTWORK_RABBIT_USERNAME}"
    password: ${smartwork_rabbitmq_pass}

sparks:
  cargo:
    oauth2:
      client:
        clientId: ${rabbitmq.username}
        clientSecret: ${rabbitmq.password}
        username: ${IPN_MAPPER_USERNAME}
        password: ${IPN_MAPPER_PASSWORD}
