rabbitmq:
  server: "${SPARKS_RABBIT_HOST}"
  port: "${SPARKS_RABBIT_PORT}"
  username: "${IPN_MAPPER_CLIENT_ID}"
  password: "${IPN_MAPPER_CLIENT_SECRET}"
  queueSend: "smartwork-ipn-send"
  serverB:
    host: "${SMARTWORK_RABBIT_HOST}"
    port: "${SMARTWORK_RABBIT_PORT}"
    username: "${SMARTWORK_RABBIT_USERNAME}"
    password: "${SMARTWORK_RABBIT_PASSWORD}"