version: '3'

services:
  piveau-hub-repo:
    image: registry.gitlab.com/piveau/hub/piveau-hub-repo:latest
    container_name: piveau-hub-repo
    restart: always
    logging:
      options:
        max-size: "50m"
    ports:
      - 8081:8080
      - 8085:8085
      - 5002:5000
    environment:
      - PIVEAU_HUB_SERVICE_PORT=8080
      - PIVEAU_HUB_SEARCH_SERVICE={"enabled":true,"url":"piveau-hub-search","port":8080,"api_key":"yourSearchApiKey"}
      - PIVEAU_HUB_API_KEY=yourRepoApiKey
      - PIVEAU_HUB_SHELL_CONFIG={"http":{},"telnet":{}}
      - PIVEAU_TRIPLESTORE_CONFIG={"address":"http://virtuoso:8890","clearGeoDataCatalogues":["*"]}
      - PIVEAU_HUB_AUTHORIZATION_PROCESS_DATA={"clientId":"piveau-hub-repo","clientSecret":"4ol2Y5ZgBXunMj3F3RFFDNKATgi79obq","tokenServerConfig":{"keycloak":{"serverUrl":"https://auth.ac3-project.eu/auth","realm":"piveau"}}}
      #      - PIVEAU_HUB_AUTHORIZATION_PROCESS_DATA.tokenServerConfig.keycloak.realm=piveau
      #      - PIVEAU_HUB_AUTHORIZATION_PROCESS_DATA.tokenServerConfig.keycloak.serverUrl=http://keycloak:8080/auth
      #      - PIVEAU_HUB_AUTHORIZATION_PROCESS_DATA.clientId=piveau-hub-repo
      #      - PIVEAU_HUB_AUTHORIZATION_PROCESS_DATA.clientSecret=947R552Apa7Jrwapn900X9u7bAcaWd4V
      #      - PIVEAU_HUB_AUTHORIZATION_PROCESS_DATA.issuer=http://keycloak:8080/auth/realms/piveau
      - JAVA_OPTS=-Xms1g -Xmx2g

  piveau-hub-search:
    image: registry.gitlab.com/piveau/hub/piveau-hub-search:latest
    container_name: piveau-hub-search
    restart: always
    logging:
      options:
        max-size: "50m"
    ports:
      - 8084:8080
      - 8086:8081
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - PIVEAU_HUB_SEARCH_API_KEY=yourSearchApiKey
      - PIVEAU_HUB_SEARCH_ES_CONFIG={"host":"elasticsearch","port":9200}
      - PIVEAU_HUB_SEARCH_GAZETTEER_CONFIG={"url":"http://doesnotmatter.eu"}
      - JAVA_OPTS=-Xms1g -Xmx2g

  piveau-hub-ui:
    image: registry.gitlab.com/piveau/hub/piveau-hub-ui:latest
    container_name: piveau-hub-ui
    restart: always
    logging:
      options:
        max-size: "50m"
    ports:
      - 8080:8080
    environment:
      - VITE_METADATA_TITLE=ac3-piveau
      - VITE_API_BASE_URL=https://search.piveau.ac3-project.eu/
      - VITE_API_HUB_URL=https://piveau.ac3-project.eu/
      - VITE_API_UPLOAD_BASE_URL=http://localhost:8088/
      - VITE_AUTHENTICATION_USE_SERVICE=true
      - VITE_AUTHENTICATION_LOGIN_USE_LOGIN=true
      - VITE_AUTHENTICATION_LOGIN_LOGIN_TITLE=Connect
      - VITE_AUTHENTICATION_LOGIN_LOGOUT_TITLE=Logout
      - VITE_AUTHENTICATION_LOGIN_LOGOUT_URL=/logout
      - VITE_AUTHENTICATION_KEYCLOAK_REALM=piveau
      - VITE_AUTHENTICATION_KEYCLOAK_CLIENT_ID=piveau-hub-ui
      - VITE_AUTHENTICATION_KEYCLOAK_URL=https://auth.ac3-project.eu/auth
      - VITE_AUTHENTICATION_KEYCLOAK_SSL_REQUIRED=external
      - VITE_AUTHENTICATION_KEYCLOAK_PUBLIC_CLIENT=true
      - VITE_AUTHENTICATION_KEYCLOAK_VERIFY_TOKEN_AUDIENCE=true
      - VITE_AUTHENTICATION_KEYCLOAK_USE_RESOURCE_ROLE_MAPPINGS=true
      - VITE_AUTHENTICATION_KEYCLOAK_CONFIDENTIAL_PORT=0
      - VITE_AUTHENTICATION_RTP_GRAND_TYPE=urn:ietf:params:oauth:grant-type:uma-ticket
      - VITE_AUTHENTICATION_RTP_AUDIENCE=piveau-hub-repo
      - VITE_ROUTER_OPTIONS_BASE=/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
    container_name: elasticsearch
    restart: always
    logging:
      options:
        max-size: "50m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl -s -f http://elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2G -Xmx4G
    volumes:
      - PV_elastic:/usr/share/elasticsearch/data

  virtuoso:
    image: openlink/virtuoso-opensource-7:7.2.9
    container_name: virtuoso
    restart: always
    logging:
      options:
        max-size: "50m"
    ports:
      - 8890:8890
      - 1111:1111
    environment:
      - DBA_PASSWORD=dba
      - VIRT_PARAMETERS_NUMBEROFBUFFERS=170000
      - VIRT_PARAMETERS_MAXDIRTYBUFFERS=130000
      - VIRT_PARAMETERS_SERVERTHREADS=100
      - VIRT_HTTPSERVER_SERVERTHREADS=100
      - VIRT_HTTPSERVER_MAXCLIENTCONNECTIONS=100
    volumes:
      - PV_virtuoso:/database

volumes:
  PV_virtuoso:
    external: true
  PV_elastic:
    external: true
