version: '3'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - './psql:/bitnami/postgresql'

  keycloak:
    image: docker.io/bitnami/keycloak:20
    depends_on:
      - postgresql
    # Enable if keycloak should run under auth path
    environment:
      - KC_HTTP_RELATIVE_PATH=/auth
    ports:
      - "8090:8080"

