version: '3'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - KEYCLOAK_DB:/bitnami/postgresql

  keycloak:
    image: docker.io/bitnami/keycloak:20
    restart: always
    depends_on:
      - postgresql
    # Enable if keycloak should run under auth path
    environment:
      - KC_HTTP_RELATIVE_PATH=/auth
      #      - KC_HOSTNAME=domain
      - KC_PROXY_ADDRESS_FORWARDING=true
      - KC_PROXY=passthrough
      #      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
    ports:
      - "8090:8080"

volumes:
  KEYCLOAK_DB:
