server:
  port: 8026

spring.main.allow-bean-definition-overriding: true

spring.rabbitmq.host: ${rabbitmq.server}
spring.rabbitmq.port: ${rabbitmq.port}
spring.rabbitmq.username: ${rabbitmq.username}
spring.rabbitmq.password: ${rabbitmq.password}

logging:
  level:
    net.sparkworks.common: DEBUG

management:
  health:
    rabbit:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 5026
  endpoint:
    metrics:
      enabled: true
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
          metric-name: 'mapper.http.metrics'

rabbitmq:
  queueCommands: "${rabbitmq.uriPrefix}-commands"
  queueSend: "${rabbitmq.uriPrefix}-send"
  queueData: data-sparks
  queueData2: data-sparks2
  queueData3: data-sparks3

mapper:
  skinresponse:
    threshold: 5

sparks:
  cargo:
    address: https://api.sparkworks.net
    internal: false
    oauth2:
      client:
        accessTokenUrl: "https://sso.sparkworks.net/aa/oauth/token"
