rabbitmq:
  server: "${RABBITMQ_HOST}"
  port: "${RABBITMQ_PORT}"
  username: "${RABBITMQ_USERNAME}"
  password: ${RABBITMQ_PASSWORD}
  uriPrefix: "ac3-data"
  queue:
    commands: "${QUEUE_COMMANDS}"
    output: "${QUEUE_OUT}"
    input: "${QUEUE_IN}"

logging:
  level:
    net.sparkworks.common: ERROR
    net.sparkworks.mapper: INFO
    org.springframework.amqp.rabbit.connection: DEBUG;
